# Generated by Django 4.1 on 2023-02-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_user_follower_alter_post_date_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
